// v0.1b:
import type { LLMProvider, LLMRequest } from '../LLMAdapter.js';
import type { AIResult, ModelCapability } from '../../../shared/types.js';
import { LLMHttpError } from '../../../shared/errors.js';
import { safeJsonParse } from '../../../shared/utils.js';

export interface AnthropicConfig {
  apiKey: string;
  model?: string;
  baseUrl?: string;
}

export class AnthropicProvider implements LLMProvider {
  readonly name = 'anthropic';
  readonly capabilities: readonly ModelCapability[] = ['chat', 'vision', 'code-generation', 'long-context', 'reasoning', 'json-mode', 'streaming'];
  private _model: string;
  private baseUrl: string;
  private apiKey: string;

  get model(): string { return this._model; }

  constructor(config: AnthropicConfig) {
    this.apiKey = config.apiKey;
    this._model = config.model || 'claude-3-haiku-20240307';
    this.baseUrl = config.baseUrl || 'https://api.anthropic.com/v1';
  }

  async isAvailable(): Promise<boolean> {
    try {
      const res = await fetch(`${this.baseUrl}/models`, {
        headers: {
          'x-api-key': this.apiKey,
          'anthropic-version': '2023-06-01',
        },
      });
      return res.ok;
    } catch {
      return false;
    }
  }

  async generate<T>(request: LLMRequest): Promise<AIResult<T>> {
    const res = await fetch(`${this.baseUrl}/messages`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': this.apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: this._model,
        messages: request.messages,
        temperature: request.temperature ?? 0.7,
        max_tokens: request.maxTokens ?? 2048,
      }),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new LLMHttpError(res.status, text);
    }

    const json = await res.json() as Record<string, unknown>;
    if (!Array.isArray(json.content) || !json.content[0] || typeof (json.content[0] as { text?: string }).text !== 'string') {
      throw new LLMHttpError(res.status, 'Invalid Anthropic response structure');
    }
    const content = (json.content[0] as { text: string }).text;
    let data: T;
    try {
      data = safeJsonParse(content) as T;
    } catch {
      throw new Error(`Anthropic provider failed to parse structured output: ${content.slice(0, 200)}`);
    }

    return {
      data,
      confidence: 0.9,
      reasoning: 'Generated by Anthropic',
      tokensUsed: (json.usage as { input_tokens?: number; output_tokens?: number } | undefined)
        ? ((json.usage as { input_tokens?: number; output_tokens?: number }).input_tokens ?? 0) + ((json.usage as { input_tokens?: number; output_tokens?: number }).output_tokens ?? 0)
        : undefined,
    };
  }
}
