// v0.2b:
import type { LLMProvider, LLMRequest } from '../LLMAdapter.js';
import type { AIResult, ModelCapability } from '../../../shared/types.js';
import { LLMHttpError } from '../../../shared/errors.js';
import { safeJsonParse } from '../../../shared/utils.js';


export interface OllamaConfig {
  baseUrl?: string;
  model?: string;
  apiKey?: string;
}

export class OllamaProvider implements LLMProvider {
  readonly name = 'ollama';
  readonly capabilities: readonly ModelCapability[] = ['chat', 'code-generation', 'embedding'];
  private _model: string;
  private baseUrl: string;
  private apiKey: string;

  get model(): string { return this._model; }

  constructor(config: OllamaConfig) {
    this._model = config.model || 'llama3.1';
    this.baseUrl = config.baseUrl || 'http://localhost:11434';
    this.apiKey = config.apiKey || '';
  }

  private headers(): Record<string, string> {
    const h: Record<string, string> = {
      'Content-Type': 'application/json',
      'Connection': 'close',
    };
    if (this.apiKey) {
      h['Authorization'] = `Bearer ${this.apiKey}`;
    }
    return h;
  }

  async isAvailable(): Promise<boolean> {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 10000);
    try {
      const res = await fetch(`${this.baseUrl}/api/tags`, {
        headers: this.apiKey ? { 'Authorization': `Bearer ${this.apiKey}` } : {},
        signal: controller.signal,
      });
      clearTimeout(timeout);
      return res.ok;
    } catch {
      clearTimeout(timeout);
      return false;
    }
  }

  async generate<T>(request: LLMRequest): Promise<AIResult<T>> {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 60000);
    try {
      const body = JSON.stringify({
        model: this._model,
        messages: request.messages,
        stream: false,
        format: request.responseSchema ? 'json' : undefined,
        options: {
          temperature: request.temperature ?? 0.7,
          num_predict: request.maxTokens ?? 2048,
        },
      });
      const res = await fetch(`${this.baseUrl}/api/chat`, {
        method: 'POST',
        headers: this.headers(),
        body,
        signal: controller.signal,
      });
      clearTimeout(timeout);

      if (!res.ok) {
        const text = await res.text().catch(() => '');
        throw new LLMHttpError(res.status, text);
      }

      const json = await res.json() as Record<string, unknown>;
      const message = json.message as { content?: string } | undefined;
      if (!message || typeof message.content !== 'string') {
        throw new LLMHttpError(res.status, 'Invalid Ollama response structure');
      }
      const content = message.content;
      if (!content || content.trim().length === 0) {
        throw new Error('Ollama returned empty content');
      }
      let data: T;
      try {
        data = safeJsonParse(content) as T;
      } catch {
        throw new Error(`Ollama provider failed to parse structured output (length=${content.length}): ${content.slice(0, 200)}`);
      }

      return {
        data,
        confidence: 0.85,
        reasoning: 'Generated by Ollama',
        tokensUsed: typeof json.prompt_eval_count === 'number' && typeof json.eval_count === 'number'
          ? json.prompt_eval_count + json.eval_count
          : undefined,
      };
    } catch (err) {
      throw err;
    } finally {
      clearTimeout(timeout);
    }
  }
}
