// v0.1b:
import type { LLMProvider, LLMRequest } from '../LLMAdapter.js';
import type { AIResult, ModelCapability } from '../../../shared/types.js';
import { LLMHttpError } from '../../../shared/errors.js';
import { safeJsonParse } from '../../../shared/utils.js';

export interface OpenAIConfig {
  apiKey: string;
  model?: string;
  baseUrl?: string;
}

export class OpenAIProvider implements LLMProvider {
  readonly name = 'openai';
  readonly capabilities: readonly ModelCapability[] = ['chat', 'function-calling', 'vision', 'code-generation', 'json-mode', 'streaming'];
  private _model: string;
  private baseUrl: string;
  private apiKey: string;

  get model(): string { return this._model; }

  constructor(config: OpenAIConfig) {
    this.apiKey = config.apiKey;
    this._model = config.model || 'gpt-4o-mini';
    this.baseUrl = config.baseUrl || 'https://api.openai.com/v1';
  }

  async isAvailable(): Promise<boolean> {
    try {
      const res = await fetch(`${this.baseUrl}/models`, {
        headers: { Authorization: `Bearer ${this.apiKey}` },
      });
      return res.ok;
    } catch {
      return false;
    }
  }

  async generate<T>(request: LLMRequest): Promise<AIResult<T>> {
    const res = await fetch(`${this.baseUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        model: this._model,
        messages: request.messages,
        temperature: request.temperature ?? 0.7,
        max_tokens: request.maxTokens ?? 2048,
        response_format: request.responseSchema ? { type: 'json_object' } : undefined,
      }),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new LLMHttpError(res.status, text);
    }

    const json = await res.json() as {
      choices: Array<{ message: { content: string } }>;
      usage?: { total_tokens: number };
    };
    const content = json.choices[0]?.message?.content ?? '{}';
    let data: T;
    try {
      data = safeJsonParse(content) as T;
    } catch {
      throw new Error(`OpenAI provider failed to parse structured output: ${content.slice(0, 200)}`);
    }

    return {
      data,
      confidence: 0.9,
      reasoning: 'Generated by OpenAI',
      tokensUsed: json.usage?.total_tokens,
    };
  }
}
